### ISSUE TITLE
Linux: Permission denied: '/dev/ttyACM0'

### ISSUE THREAD

**Issue by electocoded** [Flairmesh/FlooPaste#2]
I installed on Ubuntu 22.04.1 and after launching, terminal reported this permission denied error. Follow instructions from this StackExchange post (https://askubuntu.com/questions/133235/how-do-i-allow-non-root-access-to-ttyusb0) to verify the ttyACM0 Arduino device is the "dailout" user group and add your $USER to the group. Suggest adding to Linux install instructions

**Comment by Flairmesh** [comment]
Thanks for the suggestion. Install instructions have been added to the README file.
